name: Python Tests

on:
  push:
    branches: [ main, dev ]  # 确保dev分支的提交会触发工作流
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # 新增调试步骤：列出所有文件
      - name: List files in CI environment
        run: ls -la
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest
