name: Python Tests

on:
  push:
    branches: [ dev, staging, main ]  # 推送这些分支时触发
  pull_request:
    branches: [ dev, staging, main ]  # 开PR到这些分支时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 用Ubuntu系统跑

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # 和Dockerfile的Python版本一致
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest tests/test_app.py -v  # 跑测试文件
